'use strict';

/**
 * @file testDb.js
 * @description Per-test-file database isolation. Every test file that
 * touches ../src/db calls createIsolatedTestDb() in test.before(), which
 * creates a brand-new, empty Postgres database unique to that run and
 * points DATABASE_URL at it before src/db.js is ever required.
 *
 * This replaces the previous setup, where every test file pointed at the
 * same shared `ebtms_test` database and reset it with DELETE FROM ... in
 * beforeEach -- workable only if test files never run at the same time as
 * each other. `--test-concurrency=1` was supposed to guarantee that, but
 * didn't reliably: node:test's own docs don't promise strict
 * one-file-fully-finishes-before-the-next-starts ordering from that flag,
 * and in practice two files' beforeEach/test bodies interleaved against
 * the same live tables, producing exactly the intermittent
 * foreign-key-violation and unexpected-500 failures this fixes. A
 * dedicated database per file removes the shared mutable state those
 * races depended on, so file-level concurrency becomes safe again instead
 * of something to avoid.
 */

require('dotenv').config();
const { Client } = require('pg');
const crypto = require('crypto');

const ADMIN_CONNECTION = process.env.TEST_ADMIN_DATABASE_URL || 'postgres://postgres:devpassword@localhost:5432/postgres';

/**
 * @param {string} label - short, filesystem/SQL-identifier-safe tag for
 *   this test file (e.g. 'tyres_route') -- purely for readability when
 *   listing databases by hand, not load-bearing for uniqueness.
 * @returns {Promise<{ dbName: string, dropTestDb: () => Promise<void> }>}
 */
async function createIsolatedTestDb(label) {
  const safeLabel = String(label).replace(/[^a-z0-9_]/gi, '_').toLowerCase();
  const dbName = `ebtms_test_${safeLabel}_${crypto.randomBytes(4).toString('hex')}`;

  const admin = new Client({ connectionString: ADMIN_CONNECTION });
  await admin.connect();
  try {
    // Database names can't be parameterized (they're identifiers, not
    // values) -- safe here regardless, since dbName is entirely
    // generated by this function, never derived from external input.
    await admin.query(`CREATE DATABASE "${dbName}"`);
  } finally {
    await admin.end();
  }

  const url = new URL(ADMIN_CONNECTION);
  url.pathname = `/${dbName}`;
  process.env.DATABASE_URL = url.toString();

  async function dropTestDb() {
    const cleanup = new Client({ connectionString: ADMIN_CONNECTION });
    await cleanup.connect();
    try {
      // Postgres refuses DROP DATABASE while any session is still
      // connected to it -- the app's own pool (src/db.js) needs to be
      // closed by the caller first via db.close(), but this is a second,
      // belt-and-suspenders guard against a connection that didn't shut
      // down cleanly (e.g. a test that threw before reaching db.close()).
      await cleanup.query(
        'SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = $1 AND pid <> pg_backend_pid()',
        [dbName]
      );
      await cleanup.query(`DROP DATABASE IF EXISTS "${dbName}"`);
    } finally {
      await cleanup.end();
    }
  }

  return { dbName, dropTestDb };
}

module.exports = { createIsolatedTestDb };
