// Tyre Card Amendment / Correction workflow: mirrors the backend's
// AMENDABLE_FIELDS (backend/src/utils/tyreEvents.js) -- which tyre_events
// columns may be corrected per event_type. Kept as a separate frontend copy
// the same way lib/roles.js already mirrors backend/src/utils/roles.js.
export const AMENDABLE_FIELDS = {
  nsd_reading: ['nsd_value', 'notes', 'nsd_g1', 'nsd_g2', 'nsd_g3', 'nsd_g4'],
  pressure_reading: ['pressure_value', 'notes'],
  rotation: ['to_position', 'reason'],
  replacement: ['reason'],
  puncture_repair: ['repair_type', 'notes', 'repair_cost', 'supervisor_name', 'tyre_man_name', 'patch_size'],
  send_to_repair: ['reason', 'nsd_value'],
  inter_bus_transfer: ['to_bus_id', 'to_position', 'reason'],
  send_to_store: ['nsd_value', 'stored_at', 'reason'],
  condemnation: ['nsd_value', 'reason'],
  purchase_intake: ['notes', 'vendor_name', 'gate_pass_no', 'invoice_no', 'invoice_date'],
  fitment_created: ['reason'],
  reservation: ['reason'],
  inspection_completed: ['notes'],
  retread_sent: ['vendor_name', 'vendor_location', 'gate_pass_no', 'reason', 'retread_purpose'],
  retread_completed: ['vendor_name', 'vendor_location', 'retread_cost', 'invoice_no', 'invoice_date', 'notes', 'outcome', 'reason'],
  warranty_claim: ['reason', 'notes', 'vendor_name', 'gate_pass_no', 'invoice_no', 'invoice_date', 'approved_by', 'vendor_location'],
  scrap: ['scrap_value', 'reason', 'vendor_name', 'vendor_location', 'gate_pass_no', 'invoice_no', 'invoice_date', 'approved_by', 'store_manager', 'nsd_value'],
  scrap_disposal: ['reason'],
};

export const FIELD_LABELS = {
  nsd_value: 'NSD',
  pressure_value: 'Pressure',
  notes: 'Notes',
  to_position: 'To Position',
  reason: 'Reason',
  repair_type: 'Repair Type',
  to_bus_id: 'Destination Bus',
  stored_at: 'Stored At',
  repair_cost: 'Repair Cost',
  retread_cost: 'Retread Cost',
  scrap_value: 'Scrap Value',
  vendor_name: 'Vendor',
  vendor_location: 'Vendor Location',
  gate_pass_no: 'Gate Pass No.',
  invoice_no: 'Invoice No.',
  invoice_date: 'Invoice Date',
  approved_by: 'Approved By',
  supervisor_name: 'Supervisor Name',
  tyre_man_name: 'Tyre Man Name',
  patch_size: 'Patch Size',
  nsd_g1: 'NSD Groove 1',
  nsd_g2: 'NSD Groove 2',
  nsd_g3: 'NSD Groove 3',
  nsd_g4: 'NSD Groove 4',
  retread_purpose: 'Purpose',
  outcome: 'Outcome',
  store_manager: 'Store Manager',
};
